name: Tabulation Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Запустить скрипт для проверки табуляции
      run: |
        bash .github/TabulationTest.sh > .github/last_log
    - name: Проверка лог файла
      run: |
        bash .github/SuccessCheck.sh
