name: Tabulation Test

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Запустить скрипт для проверки табуляции
      run: |
        bash .github/TabulationTest.sh
